miatoll: Patch libwfdservice to load android.media.audio.common.types-V4-cpp.so
Fixes:
error: module "libwfdservice" variant "android_arm64_armv8-2a_cortex-a76_static":
depends on multiple versions of the same aidl_interface:
android.media.audio.common.types-V3-cpp-source,
android.media.audio.common.types-V4-cpp-source